set(_CATKIN_CURRENT_PACKAGE "organ_slam")
set(organ_slam_VERSION "0.0.0")
set(organ_slam_MAINTAINER "advaith <advaith@todo.todo>")
set(organ_slam_PACKAGE_FORMAT "2")
set(organ_slam_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(organ_slam_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(organ_slam_BUILDTOOL_DEPENDS "catkin")
set(organ_slam_BUILDTOOL_EXPORT_DEPENDS )
set(organ_slam_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(organ_slam_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(organ_slam_TEST_DEPENDS )
set(organ_slam_DOC_DEPENDS )
set(organ_slam_URL_WEBSITE "")
set(organ_slam_URL_BUGTRACKER "")
set(organ_slam_URL_REPOSITORY "")
set(organ_slam_DEPRECATED "")